import type { Metadata } from "next";

import { Poppins } from "next/font/google";
import "./globals.css";
import { domAnimation, LazyMotion } from "motion/react";
import InnerLayout from "@/components/InnerLayout";
import { CounterStoreProvider } from "@/providers/counter-store-provider";

const poppins = Poppins({
  subsets: ["latin"], // Choose language subsets as needed
  weight: ["200", "300", "400", "500", "700"], // Include only the weights you use
  variable: "--font-poppins", // Optional CSS variable
  preload: true, // Ensures the font is preloaded automatically
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${poppins.className} antialiased flex min-h-full flex-col `}
      >
        <LazyMotion features={domAnimation}>
          <CounterStoreProvider>
            <InnerLayout>{children}</InnerLayout>
          </CounterStoreProvider>
        </LazyMotion>
      </body>
    </html>
  );
}
