import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { Poppins } from "next/font/google";
import "./globals.css";
import { domAnimation, LazyMotion } from "motion/react";

import { UnifiedStoreProvider } from "@/providers/unified-store-provider";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const poppins = Poppins({
  subsets: ["latin"], // Choose language subsets as needed
  weight: ["200", "300", "400", "500", "700"], // Include only the weights you use
  variable: "--font-poppins", // Optional CSS variable
  preload: true, // Ensures the font is preloaded automatically
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full">
      <body
        className={`${poppins.className} antialiased flex min-h-full flex-col `}
      >
        <LazyMotion features={domAnimation}>
          <UnifiedStoreProvider>
            <Header />
            <main className="w-full flex-1 ">{children}</main>
            <Footer />
            <div id="modal-root"></div>
            <Toaster />
          </UnifiedStoreProvider>
        </LazyMotion>
      </body>
    </html>
  );
}
